name: Scan Codespace

env:
 token: ${{ secrets.TOKEN }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'

      - name: Build and run scripts
        run: |
          docker run --rm -v "$(pwd)":/app -w /app ruby:latest bash -c "chmod +x languages.sh comment.sh && ./languages.sh && ./comment.sh"
