env:
  token: ${{ secrets.TOKEN }}
  
name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Build and Test
        run: |
          gem install github-linguist

      - name: Run languages.sh
        run: |
          chmod +x ./languages.sh
          ./languages.sh
        shell: bash

      - name: Run comment.sh
        run: |
          chmod +x comment.sh
          ./comment.sh
        shell: bash
